### ISSUE TITLE
cannot build using Python 3.5.1

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus_core#277]
```
% ./waf configure --prefix=/tmp/jubatus
Setting top to                           : /home/jubatus/Development/jubatus_core 
Setting out to                           : /home/jubatus/Development/jubatus_core/build 
Checking for 'g++' (c++ compiler)        : ok 
Unpacking gtest                          : yes 
Traceback (most recent call last):
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Scripting.py", line 93, in waf_entry_point
    run_commands()
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Scripting.py", line 145, in run_commands
    run_command(cmd_name)
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Scripting.py", line 138, in run_command
    ctx.execute()
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Configure.py", line 127, in execute
    super(ConfigurationContext,self).execute()
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Context.py", line 127, in recurse
    user_function(self)
  File "/home/jubatus/Development/jubatus_core/wscript", line 45, in configure
    conf.load('unittest_gtest')
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Configure.py", line 189, in load
    if type(func)is type(Utils.readf):func(self)
  File "/home/jubatus/Development/jubatus_core/unittest_gtest.py", line 107, in configure
    conf.check_cxx(lib = 'pthread', uselib_store = 'GTEST_PTHREAD')
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Configure.py", line 220, in fun
    return f(*k,**kw)
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Tools/c_config.py", line 447, in check_cxx
    return self.check(*k,**kw)
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Configure.py", line 220, in fun
    return f(*k,**kw)
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Tools/c_config.py", line 356, in check
    ret=self.run_c_code(*k,**kw)
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Configure.py", line 220, in fun
    return f(*k,**kw)
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Tools/c_config.py", line 434, in run_c_code
    bld.compile()
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Build.py", line 191, in compile
    self.store()
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Utils.py", line 302, in f
    ret=fun(*k,**kw)
  File "/home/jubatus/Development/jubatus_core/.waf3-1.6.4-37059750328bf24b869521d97d29c0c1/waflib/Build.py", line 165, in store
    cPickle.dump(data,f)
AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'
```

**Comment by kmaehashi** [comment]
Fixed via #308.
