### ISSUE TITLE
NN-Classifier: put_diff fails with _GLIBCXX_DEBUG defined

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus_core#307]
``jubaclassifier`` abort when build with ``_GLIBCXX_DEBUG``.

```
 :
2016-08-03 11:43:39,326 5863 DEBUG [linear_mixer.cpp:200] put diff to xxx.xx.xxx.x:9199
/usr/include/c++/4.6/debug/vector:313:error: attempt to subscript container
    with out-of-bounds index 0, but container only holds 0 elements.

Objects involved in the operation:
sequence "this" @ 0x0x7f75f8004aa8 {
  type = NSt7__debug6vectorIN7msgpack6objectESaIS2_EEE;
}
Aborted (core dumped)
```

* config:

  ```
{
  "converter" : {
    "string_filter_types" : {},
    "string_filter_rules" : [],
    "num_filter_types" : {},
    "num_filter_rules" : [],
    "string_types" : {},
    "string_rules" : [
      { "key" : "*", "type" : "str", "sample_weight" : "bin", "global_weight" : "bin" }
    ],
    "num_types" : {},
    "num_rules" : [
      { "key" : "*", "type" : "num" }
    ]
  },
  "method" : "NN",
  "parameter": {
    "method": "euclid_lsh",
    "parameter": {
      "hash_num": 64
    },
    "nearest_neighbor_num": 128,
    "local_sensitivity": 1,
    "unlearner": "random",
    "unlearner_parameter": {
      "max_size": 10000
    }
  }
}
  ```

* BackTrace

  ```
#0  0x00007f7612fb5035 in __GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007f7612fb879b in __GI_abort () at abort.c:91
#2  0x00007f76137d25ad in __gnu_debug::_Error_formatter::_M_error() const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f7614c2fec8 in std::__debug::vector<msgpack::object, std::allocator<msgpack::object> >::operator[] (this=0x7f75f8004aa8, __n=0) at /usr/include/c++/4.6/debug/vector:313
#4  0x00007f7614d9ab40 in operator[] (__n=0, this=<optimized out>) at /usr/include/c++/4.6/debug/vector:313
#5  jubatus::core::framework::mixable_versioned_table::put_diff (this=0x6c5f80, ptr=...) at ../jubatus/core/framework/mixable_versioned_table.cpp:101
#6  0x00007f7614cdb1a4 in jubatus::core::driver::driver_base::mixable_holder::put_diff (this=0x6f1d28, obj=...) at ../jubatus/core/driver/driver.cpp:173
#7  0x00007f7615aefcde in jubatus::server::framework::mixer::linear_mixer::put_diff (this=0x6a81b0, diff=...) at ../jubatus/server/framework/mixer/linear_mixer.cpp:629
  ```

**Comment by kmaehashi** [comment]
Fixed via #310.
